fos_rest:
    view:
        view_response_listener: 
            enabled: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: ^/, priorities: ['html'], fallback_format: html, prefer_extension: false  }
    serializer:
        serialize_null: true
    exception:
        codes:
            'App\Exception\GithubAuthorizationException': 401
            'App\Exception\GithubResourceNotFoundException': 404
            'App\Exception\GithubConnectionException': 503
        messages:
            'App\Exception\GithubAuthorizationException': true
            'App\Exception\GithubResourceNotFoundException': true
            'App\Exception\GithubConnectionException': true